import Link from "next/link";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className="relative min-h-screen">
          {children}
          <footer className="fixed bottom-0 left-0 w-full bg-neutral-100 dark:bg-neutral-800 py-4">
            <div className="container mx-auto flex justify-center">
              <Link 
                href="/preview" 
                className="text-neutral-600 dark:text-neutral-300 hover:text-neutral-900 dark:hover:text-neutral-100 transition-colors"
              >
                Chat
              </Link>
            </div>
          </footer>
        </div>
      </body>
    </html>
  )
}
